server:
  port: 9012
spring:
  application:
    name: cloud-web

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  # 走线上 模块之间可以跨域访问
  instance:
    prefer-ip-address: true

zuul:
  routes:
    cloud-base:
      #要访问的路径   只要访问的路径里面有/base  自动跳到base模块里
      path: /base/**
      serviceId: cloud-base
    cloud-user:
      #要访问的路径   只要访问的路径里面有/base  自动跳到base模块里
      path: /user/**
      serviceId: cloud-user
    cloud-qa:
      #要访问的路径   只要访问的路径里面有/base  自动跳到base模块里
      path: /qa/**
      serviceId: cloud-qa



