server:
  port: 9009
spring:
  rabbitmq:
    host: 192.168.33.129
aliyun:
  sms:
    accessKeyId: LTAIxo9ZQy1tSHYL
    accessKeySecret: IawJXWPq1MvG691zCcE0BoyvGvwE5G
    template_code: SMS_94700095
    sign_name: 李腾飞自己做短信测试